server:
    port: 9090
    servlet:
        context-path: /demo

dubbo:
    application:
        name: spring-boot-demo-dubbo-provider
    registry:
        address: zookeeper://47.101.165.21:2181
        timeout: 10000
    protocol:
        name: dubbo
        port: 20890
    # 扫描 @DubboService 注解
    scan:
        base-packages: com.xkcoding.dubbo.provider.service

