server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  rabbitmq:
    host: 192.168.3.138
    port: 30607
    username: user
    password: user
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
