server:
    port: 8080
    servlet:
        context-path: /demo
spring:
    mvc:
        pathmatch:
            # 配置策略
            # https://blog.csdn.net/weixin_44888725/article/details/127070665
            matching-strategy: ant-path-matcher
