spring:
    datasource:
        url: jdbc:mysql://192.168.3.138:30467/study?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialization-mode: always
        continue-on-error: true
        schema:
            - "classpath:db/schema.sql"
        data:
            - "classpath:db/data.sql"
        #druid配置
        initialSize: 5 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
        minIdle: 10 # 最小连接池数量
        maxActive: 200 # 最大连接池数量
        maxWait: 60000 # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置
        timeBetweenEvictionRunsMillis: 60000 # 关闭空闲连接的检测时间间隔.Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
        minEvictableIdleTimeMillis: 300000 # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
        validationQuery: SELECT 1 FROM DUAL # 验证数据库服务可用性的sql.用来检测连接是否有效的sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
        testWhileIdle: true # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效.建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRun
        testOnBorrow: false # 申请连接时直接检测连接是否有效.申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnReturn: false # 归还连接时检测连接是否有效.归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        poolPreparedStatements: true # 开启PSCache
        maxPoolPreparedStatementPerConnectionSize: 20 #设置PSCache值
        connectionErrorRetryAttempts: 3 # 连接出错后再尝试连接三次
        breakAfterAcquireFailure: true # 数据库服务宕机自动重连机制
        timeBetweenConnectErrorMillis: 300000 # 连接出错后重试时间间隔
        asyncInit: true # 异步初始化策略
        remove-abandoned: true # 是否自动回收超时连接
        remove-abandoned-timeout: 1800 # 超时时间(以秒数为单位)
        transaction-query-timeout: 6000 # 事务超时时间
        filters: stat,wall,log4j2# 通过别名的方式配置扩展插件，多个英文逗号分隔，常用的插件有：监控统计用的filter:stat/日志用的filter:log4j/防御sql注入的filter:wall
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #    web-stat-filter:
    #      enabled: true
    #      url-pattern: "/*"
    #      exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    #    stat-view-servlet:
    #      url-pattern: "/druid/*"
    #      allow:
    #      deny:
    #      reset-enable: false
    #      login-username: admin
    #      login-password: admin
    thymeleaf:
        mode: HTML
        cache: false

logging:
    level:
        com.xkcoding: debug
        com.xkcoding.orm.mybatis.plus.mapper: trace
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.ycy.druid.domain
    global-config:
        # 数据库相关配置
        db-config:
            #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: auto
            #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
            field-strategy: not_empty
            #驼峰下划线转换
            table-underline: true
            #是否开启大写命名，默认不开启
            #capital-mode: true
            #逻辑删除配置
            logic-delete-value: 1
            logic-not-delete-value: 0
            db-type: mysql
        #刷新mapper 调试神器
        refresh: true
    # 原生配置
    configuration:
        # 配置slq打印日志
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
        cache-enabled: true
