server:
    port: 8080
    servlet:
        context-path: /demo

dubbo:
    application:
        name: spring-boot-demo-dubbo-consumer
    registry:
        address: zookeeper://47.101.165.21:2181
        timeout: 10000
    protocol:
        name: dubbo
        port: 20890
