spring:
    redis:
        host: 192.168.3.138
        port: 32674
        password: xx5320980.
        # 连接超时时间（记得添加单位，Duration）
        timeout: 10000ms
        # Redis默认情况下有16个分片，这里配置具体使用的分片
        database: 6
        lettuce:
            pool:
                # 连接池最大连接数（使用负值表示没有限制） 默认 8
                max-active: 8
                # 连接池中的最大空闲连接 默认 8
                max-idle: 8
                # 连接池中的最小空闲连接 默认 0
                min-idle: 0
                # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
                max-wait: -1ms
    cache:
        # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
        type: redis
        redis:
            time-to-live: 3600000 #过期时间
            key-prefix: CACHE_ #缓存前缀
            use-key-prefix: true #是否用前缀
            cache-null-values: true #是否缓存控制
logging:
    level:
        com.xkcoding: debug
