server:
  port: 8089
spring:
  elasticsearch:
    uris: 192.168.3.137:31364,192.168.3.138:31364
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.138:30467/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.3.138
    port: 30607
    username: user
    password: user
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS

mybatis-plus:
  # 原生配置
  configuration:
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.xkcoding.elasticsearch.pojo
